### ISSUE TITLE
Support Windows Nodes

### ISSUE THREAD

**Issue by 1WindowsPuppetAdmin** [cyberark/conjur-puppet#14] opened 2018-10-26 06:37 UTC
This module should support windows nodes. We need passwords too. :)

**Comment by jvanderhoof** [comment] 2019-03-21 16:36
@1WindowsPuppetAdmin: we've got two stories bring some Windows love to the module:
- #21 
- #22 
This will add Windows support for enrolling nodes and delivering credentials.

**Comment by dividedmind** [comment] 2019-06-10 21:10
Closing as duplicate of #24.

**Closed by dividedmind** 2019-06-10 21:10 UTC
Labels: triage/duplicate
