### ISSUE TITLE
Puppet 6 compatibility

### ISSUE THREAD

**Issue by Wernervdmerwe** [cyberark/conjur-puppet#15] opened 2018-11-23 02:57 UTC
The metadata file pin this module to <5, Puppet is now in version 6, can this be updated?

**Comment by jvanderhoof** [comment] 2019-03-21 16:32
@Wernervdmerwe: We're about to kick off an effort to leverage Deferred Types (#13).  I know this goes well beyond the ask here, but that work should resolve this issue.

**Comment by turbodog** [comment] 2019-06-04 16:14
Seconding the request to indicate Puppet 6 compatibility. Open Source is up to version 6.4 now and this also ships in current Puppet Enterprise 2019.x.

**Comment by jvanderhoof** [comment] 2019-06-04 18:15
@turbodog, we're very close to a new release which brings Windows support.  We're in the process of adding integration tests using Puppet 6.  We'll get this resolved soon.

**Comment by turbodog** [comment] 2019-06-04 21:37
Awesome!

**Comment by dividedmind** [comment] 2019-06-10 21:09
Closing this as duplicate of #20 .

**Closed by dividedmind** 2019-06-10 21:09 UTC
Labels: triage/duplicate
