### ISSUE TITLE
Run code quality metrics in CI

### ISSUE THREAD

**Issue by dividedmind** [cyberark/conjur-puppet#32] opened 2019-06-10 20:56 UTC
Code quality metrics, such as test coverage, should be gathered by CI run. We should also configure CodeClimate for this repository while we're at it.

**Comment by andytinkham** [comment] 2020-01-28 22:27
Closing because we'll be addressing these in a number of tickets, piece by piece.

**Comment by sgnn7** [comment] 2020-08-25 14:25
Duplicate of #121. Closing.

**Closed by sgnn7** 2020-08-25 14:25 UTC
